"""Responsive breakpoint generator — produces tokens, media queries, and helpers.

Docs: responsive.doc.md
"""
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


DEFAULT_BREAKPOINTS: List[Dict[str, Any]] = [
    {"name": "xs", "min": 0, "max": 479, "device": "small phone"},
    {"name": "sm", "min": 480, "max": 767, "device": "large phone"},
    {"name": "md", "min": 768, "max": 1023, "device": "tablet"},
    {"name": "lg", "min": 1024, "max": 1439, "device": "laptop"},
    {"name": "xl", "min": 1440, "max": 1919, "device": "desktop"},
    {"name": "2xl", "min": 1920, "max": None, "device": "wide desktop"},
]


@dataclass
class ResponsiveTokens:
    """All responsive design tokens — breakpoints, container widths, typography."""

    breakpoints: List[Dict[str, Any]]
    container_max_widths: Dict[str, str]
    fluid_typography: Dict[str, Any]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "breakpoints": self.breakpoints,
            "container_max_widths": self.container_max_widths,
            "fluid_typography": self.fluid_typography,
        }


class BreakpointGenerator:
    """Generate responsive design tokens and CSS media-query blocks."""

    def __init__(self) -> None:
        self.breakpoints = DEFAULT_BREAKPOINTS

    def tokens(self) -> ResponsiveTokens:
        """Return the standard responsive token set."""
        return ResponsiveTokens(
            breakpoints=list(self.breakpoints),
            container_max_widths={
                "xs": "100%",
                "sm": "100%",
                "md": "720px",
                "lg": "960px",
                "xl": "1140px",
                "2xl": "1320px",
            },
            fluid_typography={
                "min_size": 14,
                "max_size": 18,
                "min_viewport": 320,
                "max_viewport": 1200,
            },
        )

    def media_query(self, name: str) -> str:
        """Return a CSS @media block for the given breakpoint (min-width)."""
        bp = self._get(name)
        if bp is None:
            raise ValueError(
                f"Unknown breakpoint: {name}. Choose from {[b['name'] for b in self.breakpoints]}."
            )
        if bp["min"] == 0:
            return f"/* {name}: {bp['device']} */"
        return f"@media (min-width: {bp['min']}px) {{ /* {name}: {bp['device']} */ }}"

    def all_media_queries(self) -> Dict[str, str]:
        """Return a map of breakpoint name → CSS @media block."""
        return {bp["name"]: self.media_query(bp["name"]) for bp in self.breakpoints}

    def css(self) -> str:
        """Return a complete CSS file with breakpoints + container widths + fluid type."""
        tokens = self.tokens()
        lines: List[str] = [
            "/* Breakpoint tokens — generated by sin-frontend-design */",
            ":root {",
        ]
        for bp in tokens.breakpoints:
            if bp["min"] > 0:
                lines.append(f"  --bp-{bp['name']}: {bp['min']}px;")
        for name, width in tokens.container_max_widths.items():
            lines.append(f"  --container-{name}: {width};")
        lines.append("}")
        lines.append("")
        lines.append("/* Media queries */")
        for bp in tokens.breakpoints:
            if bp["min"] > 0:
                lines.append(
                    f"@media (min-width: {bp['min']}px) {{ .container {{ max-width: var(--container-{bp['name']}); }} }}"
                )
        return "\n".join(lines) + "\n"

    def test(self, viewport_width: int) -> str:
        """Return the breakpoint name that matches the given viewport width."""
        for bp in self.breakpoints:
            max_w = bp["max"] if bp["max"] is not None else float("inf")
            if bp["min"] <= viewport_width <= max_w:
                return bp["name"]
        return self.breakpoints[-1]["name"]

    def _get(self, name: str) -> Optional[Dict[str, Any]]:
        for bp in self.breakpoints:
            if bp["name"] == name:
                return bp
        return None
